# Generated by Django 5.1 on 2025-02-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_allowlist_blocklist_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='time',
            field=models.FloatField(),
        ),
    ]
