# Generated by Django 5.1 on 2025-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_plant_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], default='red', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('url', 'URL'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
