# Generated by Django 5.1 on 2025-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_note_color_note_type_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(choices=[('TDPU', 'Toshkent davlat pedagogika universiteti'), ('QDPI', "Qo'qon davlat pedagogika instituti"), ('UzFiPI', "O'zbekiston Finlandiya pedagogika instituti")], default=' ', max_length=10),
        ),
    ]
